### ISSUE TITLE
Can not migrate the database

### ISSUE THREAD

**Issue by pubestpubest** [Lolorpof/SE_backend-db#1]
### Is there anything I am missing in .env file ?
<img width="344" alt="image" src="https://github.com/user-attachments/assets/09759d1b-936f-4f2b-80f6-02bd105444bd">

> I'll have to change it later for exposed it, but whatever.

- I have to change the port to 5433 (5432 already in used).
- The container running fine.
- The server is running fine .
- Investigate via DBeaver by super user.
    - No table create yet.
    - No user "appuser".
<img width="438" alt="image" src="https://github.com/user-attachments/assets/b51ee3ec-67b2-4080-860f-6d1c3155fd19">

> Don't want to change anything yet, until the GitFlow thing is discussed.

```
pubest@pubest-2 se_backend % pnpm run db:migrate

> se_backend-db@1.0.0 db:migrate /Users/pubest/gits/se_backend
> drizzle-kit migrate

No config path provided, using default 'drizzle.config.ts'
Reading config file '/Users/pubest/gits/se_backend/drizzle.config.ts'
Using 'pg' driver for database querying
[⣷] applying migrations...error: password authentication failed for user "appuser"
    at /Users/pubest/gits/se_backend/node_modules/.pnpm/pg-pool@3.7.0_pg@8.13.1/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at PgDialect.migrate (/Users/pubest/gits/se_backend/node_modules/.pnpm/drizzle-orm@0.36.4_@types+pg@8.11.10_pg@8.13.1/node_modules/src/pg-core/dialect.ts:85:3)
    at migrate (/Users/pubest/gits/se_backend/node_modules/.pnpm/drizzle-orm@0.36.4_@types+pg@8.11.10_pg@8.13.1/node_modules/src/node-postgres/migrator.ts:10:2) {
  length: 103,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '321',
  routine: 'auth_failed'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by pubestpubest** [comment]
I just manually run script in pgAdmin to add appeaser
